---

name: 'Test'
# description: 'Demonstrates the different levels of job.status'

on: [workflow_dispatch]

jobs:
  control-group:
    name: 'Fails within this workflow itself'
    runs-on: ubuntu-latest
    steps:
      - name: 'Fail'
        id: fail
        shell: bash
        run: exit 1
    
      - name: 'Catch all'
        shell: bash
        run: echo ${{ job.status }}
        if: always()

  local-composite-action:
    name: 'Fails within the local composite action'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      
      - name: 'Failing local composite action'
        uses: ./.github/actions/do-something
      
      - name: 'Catch all'
        shell: bash
        run: echo ${{ job.status }}
        if: always()

  reusable-workflow:
    name: 'Fails within the reusable workflow'
    uses: ./.github/workflows/reusable-workflow.yml

  repo-composite-action:
    name: 'Fails within the repo composite action'
    runs-on: ubuntu-latest
    steps:
      - name: 'Failing repo composite action'
        uses: mike-carey/ghactions-test-job-status@main
      
      - name: 'Catch all'
        shell: bash
        run: echo ${{ job.status }}
        if: always()

  catch-all:
    name: 'A catch all for jobs'
    runs-on: ubuntu-latest
    if: always()
    needs:
      - control-group
      - local-composite-action
      - reusable-workflow
      - repo-composite-action
    steps:
      - name: 'Control group result'
        shell: bash
        run: echo ${{ needs.control-group.result }}

      - name: 'Local composite action result'
        shell: bash
        run: echo ${{ needs.local-composite-action.result }}

      - name: 'Reusable workflow result'
        shell: bash
        run: echo ${{ needs.reusable-workflow.result }}

      - name: 'Repo composite action result'
        shell: bash
        run: echo ${{ needs.repo-composite-action.result }}
